### ISSUE TITLE
Flags in header

### ISSUE THREAD

**Issue by unseen1980** [nuxt/nuxtjs.org#84] opened 2017-10-25 14:01 UTC
Hi all,

I would like to point something that from UI perspective doesn't look that nice. In [header](https://github.com/nuxt/nuxtjs.org/blob/df6c19d2980b45dd610a37188f81dc5a2d375a52/components/HeaderNavLang.vue), the language selection is represented by flag icons. This is not following the best practices and in some cases, it might be offensive to the users. Imagine an Irish/American/Australian etc. user having to select the United Kingdom flag. First google result about the topic brings this link http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

Is it something we can change? 

Regards 
Christos

**Comment by Atinux** [comment] 2017-11-15 09:23
Duplicate of https://github.com/nuxt/nuxtjs.org/issues/62

**Closed by Atinux** 2017-11-15 09:23 UTC
