### ISSUE TITLE
Contributors images are not loaded

### ISSUE THREAD

**Issue by larbish** [nuxt/nuxtjs.org#1937] opened 2021-11-17 17:28 UTC
Here for example: https://nuxtjs.org/docs/internals-glossary/context/

![image](https://user-images.githubusercontent.com/7290030/142251234-d9f50c07-29bb-4462-ae53-12d69e67470f.png)

**Comment by smarroufin** [comment] 2021-11-17 17:39
Duplicate of #1936

**Closed by smarroufin** 2021-11-17 17:39 UTC
Labels: bug
